const feeds = [
  // ── Original Sources ──
  {
    name: "Towards Data Science",
    url: "https://towardsdatascience.com/feed",
    siteUrl: "https://towardsdatascience.com",
    category: "AI/ML",
    color: "#1a73e8",
  },
  {
    name: "Google AI Blog",
    url: "https://blog.google/technology/ai/rss/",
    siteUrl: "https://blog.google/technology/ai/",
    category: "AI",
    color: "#34a853",
  },
  {
    name: "OpenAI Blog",
    url: "https://openai.com/blog/rss.xml",
    siteUrl: "https://openai.com/blog",
    category: "AI",
    color: "#10a37f",
  },
  {
    name: "Dev.to",
    url: "https://dev.to/feed",
    siteUrl: "https://dev.to",
    category: "Software Engineering",
    color: "#3b49df",
  },
  {
    name: "The Pragmatic Engineer",
    url: "https://newsletter.pragmaticengineer.com/feed",
    siteUrl: "https://newsletter.pragmaticengineer.com",
    category: "Software Engineering",
    color: "#ff6b35",
  },
  {
    name: "Martin Fowler",
    url: "https://martinfowler.com/feed.atom",
    siteUrl: "https://martinfowler.com",
    category: "Software Engineering",
    color: "#7c3aed",
  },
  {
    name: "Hugging Face Blog",
    url: "https://huggingface.co/blog/feed.xml",
    siteUrl: "https://huggingface.co/blog",
    category: "AI/ML",
    color: "#ffd21e",
  },
  {
    name: "Sebastian Raschka",
    url: "https://sebastianraschka.com/rss_feed.xml",
    siteUrl: "https://sebastianraschka.com",
    category: "ML",
    color: "#e11d48",
  },
  {
    name: "Stack Overflow Blog",
    url: "https://stackoverflow.blog/feed/",
    siteUrl: "https://stackoverflow.blog",
    category: "Software Engineering",
    color: "#f48024",
  },
  {
    name: "Netflix Tech Blog",
    url: "https://netflixtechblog.com/feed",
    siteUrl: "https://netflixtechblog.com",
    category: "Software Engineering",
    color: "#e50914",
  },
  {
    name: "AWS Machine Learning",
    url: "https://aws.amazon.com/blogs/machine-learning/feed/",
    siteUrl: "https://aws.amazon.com/blogs/machine-learning/",
    category: "ML",
    color: "#ff9900",
  },
  {
    name: "Andrej Karpathy",
    url: "http://karpathy.github.io/feed.xml",
    siteUrl: "https://karpathy.github.io",
    category: "AI/ML",
    color: "#818cf8",
  },

  // ── New Sources ──
  {
    name: "MIT Technology Review",
    url: "https://www.technologyreview.com/feed/",
    siteUrl: "https://www.technologyreview.com",
    category: "AI",
    color: "#c0392b",
  },
  {
    name: "Simon Willison",
    url: "https://simonwillison.net/atom/everything/",
    siteUrl: "https://simonwillison.net",
    category: "AI",
    color: "#0ea5e9",
  },
  {
    name: "fast.ai Blog",
    url: "https://www.fast.ai/index.xml",
    siteUrl: "https://www.fast.ai",
    category: "ML",
    color: "#00a86b",
  },
  {
    name: "BAIR Blog",
    url: "https://bair.berkeley.edu/blog/feed.xml",
    siteUrl: "https://bair.berkeley.edu/blog",
    category: "AI",
    color: "#003262",
  },
  {
    name: "Eugene Yan",
    url: "https://eugeneyan.com/rss/",
    siteUrl: "https://eugeneyan.com",
    category: "ML",
    color: "#06b6d4",
  },
  {
    name: "Weights & Biases",
    url: "https://wandb.ai/fully-connected/feed.xml",
    siteUrl: "https://wandb.ai/fully-connected",
    category: "ML",
    color: "#ffcc00",
  },
  {
    name: "The Gradient",
    url: "https://thegradient.pub/rss/",
    siteUrl: "https://thegradient.pub",
    category: "AI/ML",
    color: "#8b5cf6",
  },
  {
    name: "Hacker News",
    url: "https://hnrss.org/frontpage",
    siteUrl: "https://news.ycombinator.com",
    category: "Software Engineering",
    color: "#ff6600",
  },
  {
    name: "Google DeepMind",
    url: "https://deepmind.google/blog/rss.xml",
    siteUrl: "https://deepmind.google/blog",
    category: "AI",
    color: "#4285f4",
  },
  {
    name: "Chip Huyen",
    url: "https://huyenchip.com/feed.xml",
    siteUrl: "https://huyenchip.com",
    category: "ML",
    color: "#f43f5e",
  },
];

export const CATEGORIES = ["All", "AI", "AI/ML", "ML", "Software Engineering"];

export default feeds;
